# https://pre-commit.com/

# required by "language: unsupported" hook config
minimum_pre_commit_version: "4.4.0"

repos:
- repo: local
  hooks:
  - id: manual-examples
    name: Extract manual examples
    language: unsupported
    entry: l3build examples
    files: |
      (?x)^(
        build\.lua$|
        doc/generic/pgf/|
        tex/generic/pgf/(lua|graphdrawing/lua)/|
        testfiles-examples/|
      )
    pass_filenames: false
