-- Regression tests for specific issues, plus a couple of core smoke tests.
--
-- These are hand-written tests (one file per issue, named after the GitHub
-- issue they cover).  Some of them generate plot data with gnuplot, so shell
-- escape is enabled for the whole suite.

testfiledir  = "testfiles-regression"
checkopts    = "-interaction=nonstopmode -shell-escape"

-- files generated by gnuplot examples, removed between different engine tests
dynamicfiles = {"*.gnuplot", "*.table"}
