-- Tests generated from the code examples in the pgfmanual
--
-- The test files in testfiles-examples are generated automatically from the
-- manual sources with
--
--     l3build examples
--
-- Each \begin{codeexample} ... \end{codeexample} block becomes one box test
-- whose typeset content is dumped to the log and compared against a reference.
--
-- The tests are run for every supported engine.  Because the box dumps differ
-- between engines, each test has an engine specific reference file
-- (name.tlg for the std engine luatex, name.<engine>.tlg for the others).
-- checkengines is left unset so that all engines from build.lua (pdftex,
-- latexdvips, latexdvisvgm, luatex, xetex) are used.

stdengine    = "luatex"
testfiledir  = "testfiles-examples"

-- Some examples call out to gnuplot to generate plot data.  Enable shell
-- escape so that they can.  Where gnuplot is unavailable the prebuilt tables
-- copied in by checkinit_hook below are used instead.
checkopts    = "-interaction=nonstopmode -shell-escape"

-- files generated by gnuplot examples, removed between engine runs
dynamicfiles = {"*.gnuplot", "*.table"}

-- Keep all \special data so that backend output is captured faithfully
maxprintline = 9999

-- Many plot examples read prebuilt data from plots/*.table (shipped with the
-- manual).  Make those available inside the test directory.
function checkinit_hook()
  mkdir(testdir .. "/plots")
  cp("*.table", "doc/generic/pgf/plots", testdir .. "/plots")
  cp("*.gnuplot", "doc/generic/pgf/plots", testdir .. "/plots")
  return 0
end
